import Weapon from "../../virtual/models/weapon";
import { ItemType } from "../../virtual/models/item";

export const weapons: { [id: string]: Weapon } = {
    toothpick: {
        id: "toothpick",
        name: "<:toothpick:974849170827522099> Toothpick",
        description: "You COULD play golf with this",
        value: 20,
        type: ItemType.weapon,
        damage: 1,
    },
    pickaxe: {
        id: "pickaxe",
        name: "<:pickaxe:974849170819125268> Pickaxe",
        description: "Looks a bit rusty but probably useful for mining.",
        value: 30,
        type: ItemType.weapon,
        damage: 1,
    },
    cottonsword: {
        id: "cottonsword",
        name: "Cotton sword",
        description: "Pretty bad. A butterknife would probably do better.",
        value: 200,
        type: ItemType.weapon,
        damage: 5,
    },
    baseballbat: {
        id: "baseballbat",
        name: "<:baseballBat:974849169065906196> Baseball bat",
        description: "Made of steel!",
        value: 299,
        type: ItemType.weapon,
        damage: 9,
    },
    pimpcane: {
        id: "pimpcane",
        name: "Pimp cane",
        description: "\"Pimpin' ain't dead 'cause I be the life line.\"",
        value: 420,
        type: ItemType.weapon,
        damage: 12,
    },
    minecraftstevediamondpickaxe: {
        id: "minecraftstevediamondpickaxe",
        name: "<:diamondPickaxe:974849168562597910>  Minecraft Steve's Diamond Pickaxe",
        description: '"We don\'t need to stripmine."',
        value: 500,
        type: ItemType.weapon,
        damage: 5,
    },
    hornystick: {
        id: "hornystick",
        name: "<:hornystick:974849169510527057> Hornystick",
        description: "Bonks hard",
        value: 690,
        type: ItemType.weapon,
        damage: 17,
    },
    chainsaw: {
        id: "chainsaw",
        name: "<:chainsaw:974849170848489513> Chainsaw",
        description: "Chainsaw goes *BRRRRRRRRRRRRRRRRR*",
        value: 800,
        type: ItemType.weapon,
        damage: 20,
    },
    lightsaber: {
        id: "lightsaber",
        name: "<:lightsaber:974849170773012500> Lightsaber",
        description: "Be careful not to get your arm cut off",
        value: 1234,
        type: ItemType.weapon,
        damage: 25,
    },
    abyssalwhip: {
        id: "abyssalwhip",
        name: "<:abyssalWhip:974849168617111572> Abyssal whip",
        description: "A weapon from the Abyss.",
        value: 1700,
        type: ItemType.weapon,
        damage: 40,
    },
    rpg7: {
        id: "<:rpg7:974849170118696970> rpg7",
        name: "RPG-7",
        description:
            "A portable, reusable, unguided, shoulder-launched, anti-tank, rocket-propelled grenade launcher.",
        value: 2400,
        type: ItemType.weapon,
        damage: 52,
    },
    minigun: {
        id: "minigun",
        name: "<:minigun:974849171184029756> Minigun",
        description: "3200 freedoms per second!",
        value: 3500,
        type: ItemType.weapon,
        damage: 75,
    },
    megagun: {
        id: "megagun",
        name: "Megagun",
        description: "Better than a minigun!",
        value: 4800,
        type: ItemType.weapon,
        damage: 110,
    },
    infinityedge: {
        id: "infinityedge",
        name: "<:infinityEdge:974849169867030548>  Infinity Edge",
        description: "Yeah, the one from from league of legends.",
        value: 6900,
        type: ItemType.weapon,
        damage: 150,
    },
    apacheattackhelictoper: {
        id: "apacheattackhelictoper",
        name: "<:apacheHelicopter:974849170546516058> Apache attack helicopter",
        description: "How do you wield this???",
        value: 9999,
        type: ItemType.weapon,
        damage: 200,
    },
    theinfinityblade: {
        id: "theinfinityblade",
        name: "<:infinityBlade:974849170504564746> The Infinity Blade",
        description:
            "A weapon created by Galath, the Worker of Secrets, to undo his invention of the Deathless.",
        value: 14000,
        type: ItemType.weapon,
        damage: 270,
    },
    mjolnir: {
        id: "mjolnir",
        name: "<:mjolnir:974849170663956530>  Mjölnir",
        description:
            "A portable, reusable, unguided, shoulder-launched, anti-tank, rocket-propelled grenade launcher.",
        value: 22000,
        type: ItemType.weapon,
        damage: 420,
    },
    infinitygauntlet: {
        id: "infinitygauntlet",
        name: "<:infinityGauntlet:974849171058225192> Infinity gauntlet",
        description:
            "You may buy it as long as you promise not to commit fully or partial genocide.",
        value: 42000,
        type: ItemType.weapon,
        damage: 690,
    },
    deathstar: {
        id: "deathstar",
        name: "<:deathStar:974849171574124585> Death star",
        description:
            "Can obliterate planets! Make sure to cover any vents which might allow an attacker to reach and shoot the vulnerable core.",
        value: 99999,
        type: ItemType.weapon,
        damage: 999,
    },
};
